# Generated by Django 5.1.7 on 2025-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("HOSTEL", "Hostel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("beds", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("geo_address", models.CharField(max_length=200)),
                ("rating", models.FloatField(default=0.0)),
                ("region", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
