# Generated by Django 5.1.7 on 2025-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("HOSTEL", "Hostel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("beds", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_to", models.DateField(blank=True, null=True)),
                (
                    "building_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "estate_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "building_no",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("district", models.CharField(blank=True, default="", max_length=200)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(blank=True)),
                ("longitude", models.FloatField(blank=True)),
                ("geo_address", models.CharField(blank=True, max_length=200)),
                ("rating", models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
