# Generated by Django 5.1.7 on 2025-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="building_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="building_no",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="district",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="estate_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="street_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
