# Generated by Django 5.1.5 on 2025-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
