# Generated by Django 5.1.5 on 2025-03-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodation_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='userID',
            field=models.IntegerField(default=0),
        ),
    ]
