# Generated by Django 5.1.3 on 2025-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0004_alter_accommodation_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="rating_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="rating_sum",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
