# Generated by Django 5.1.7 on 2025-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0004_alter_accommodation_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
