# Generated by Django 5.1.3 on 2025-04-15 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0005_accommodation_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="rating_sum",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="AccommodationRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_identifier", models.CharField(max_length=200)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="accommodation.accommodation",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "user_identifier")},
            },
        ),
    ]
