# Generated by Django 5.1.7 on 2025-04-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0002_add_unique_address_fields"),
        (
            "accommodation",
            "0006_accommodation_rating_count_accommodation_rating_sum_and_more",
        ),
    ]

    operations = []
