# Generated by Django 5.1.7 on 2025-04-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0003_add_university_models"),
        ("accommodation", "0008_alter_accommodation_flat_number_and_more"),
    ]

    operations = []
