# Generated by Django 5.1.7 on 2025-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0010_universityapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="affiliated_universities",
            field=models.ManyToManyField(
                blank=True,
                help_text="The university that provides this accommodation",
                related_name="listed_accommodations",
                through="accommodation.AccommodationUniversity",
                to="accommodation.university",
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="flat_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="floor_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="room_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="code",
            field=models.CharField(
                help_text="University codes, such as HKU, HKUST and CUHK etc.",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(
                help_text="Full name of the university", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="specialist_email",
            field=models.EmailField(
                help_text="The email address of the accommodation expert of this university",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="universityapikey",
            name="key",
            field=models.CharField(
                help_text="API key, used for authentication requests",
                max_length=64,
                unique=True,
            ),
        ),
    ]
