# Generated by Django 5.1.7 on 2025-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0012_accommodation_contract_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="reservation_contact_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
