# Generated by Django 5.1.7 on 2025-05-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0013_accommodation_reservation_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(help_text="预定学生的ID", max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(help_text="预定开始日期")),
                ("end_date", models.DateField(help_text="预定结束日期")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_periods",
                        to="accommodation.accommodation",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
