# Generated by Django 5.1.7 on 2025-05-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0014_reservationperiod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="reserved",
        ),
    ]
