# Generated by Django 5.1.7 on 2025-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0015_remove_accommodation_reserved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="contract_status",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="reservation_contact_number",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="userID",
        ),
        migrations.AddField(
            model_name="reservationperiod",
            name="contract_status",
            field=models.BooleanField(
                default=False,
                help_text="Whether this reservation has a signed contract",
            ),
        ),
        migrations.AlterField(
            model_name="reservationperiod",
            name="end_date",
            field=models.DateField(help_text="Reservation end date"),
        ),
        migrations.AlterField(
            model_name="reservationperiod",
            name="start_date",
            field=models.DateField(help_text="Reservation start date"),
        ),
        migrations.AlterField(
            model_name="reservationperiod",
            name="user_id",
            field=models.CharField(help_text="Student's ID", max_length=255),
        ),
    ]
